export { default as Nav } from "./Nav";
export { default as Hero } from "./Hero";
export { default as Stats } from "./Stats";
export { default as Features } from "./Features";
export { default as HowItWorks } from "./HowItWorks";
export { default as Calculator } from "./Calculator";
export { default as Testimonials } from "./Testimonials";
export { default as CTA } from "./CTA";
export { default as Footer } from "./Footer";
